### ISSUE TITLE
Training error

### ISSUE THREAD

**Issue by handsomelys** [luyug/COIL#22]
When I followed the usage to train COIL, some error accurred:
`Traceback (most recent call last):
  File "run_marco.py", line 301, in <module>
    main()
  File "run_marco.py", line 81, in main
    parser = HfArgumentParser((ModelArguments, DataArguments, COILTrainingArguments))
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/hf_argparser.py", line 52, in __init__
    self._add_dataclass_arguments(dtype)
  File "/root/miniconda3/lib/python3.8/site-packages/transformers/hf_argparser.py", line 93, in _add_dataclass_arguments
    elif hasattr(field.type, "__origin__") and issubclass(field.type.__origin__, List):
  File "/root/miniconda3/lib/python3.8/typing.py", line 774, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class`
I followed the environment in README, and don't know how to fix this error ..

**Comment by handsomelys** [comment]
this problem is solved by replace python3.8 with python3.7

**Comment by zranwang** [comment]
Have you downloaded the training dataset (psg-train-d2q)? Would it be possible for you to provide me with a copy? Thank you very much
